### ISSUE TITLE
Open Source Lizenz

### ISSUE THREAD

**Issue by skriesch** [joeyboey/vawi-wa#3]
Ich bin VaWi-Studentin und habe dieses Latex-Template gefunden.
Leider ist keine Open Source Lizenz integriert, weshalb wir als VaWi-Studenten dieses Projekt nicht wiederverwenden dürfen (urheberrechtlich geschützt).

Kannst Du bitte diesem Projekt eine Lizenz hinzufügen (kann man über Github automatisch auswählen)? Für Hochschul-Zwecke werden hier meistens MIT oder Apache2.0 als Lizenzen genutzt. 

Danke!

**Comment by joeyboey** [comment]
Hey :) Na klar, bin in 2 Stunden zuhause.

**Comment by joeyboey** [comment]
Erledigt mit e032828

Sorry nochmal für die Verspätung.
